// Builder directory, both sides.
//
// HOMEOWNER reads go through the restricted view builders_public (migration
// 0006): approved, active builders, directory columns only, for paid
// homeowners. Before 0006 is applied the view does not exist, so every read
// falls back to the 0005 table select with HOMEOWNER_BUILDER_COLUMNS and the
// app keeps working. Saves and introduction requests write only the
// homeowner's own rows.
//
// BUILDER (role "pro") calls go through security-definer RPCs that find the
// caller's OWN row through owner_user_id: my_builder, save_my_builder,
// submit_my_builder, my_referral_stats. A builder never reads anything about a
// homeowner here; the stats are aggregate counts.
//
// The principle from the 2026-09-24 call: ADUAtlas helps the homeowner find
// the right builder; it does not sell open access to the homeowner.
import { supabase, supabaseEnabled } from "./supabase";

const BUCKET = "builders";
const PUBLIC_VIEW = "builders_public";
const MAX_SUGGESTIONS = 5;

export const SPECIALTY_LABELS = {
  detached: "Detached ADU",
  attached: "Attached ADU",
  garage_conversion: "Garage conversion",
  jadu: "Interior / JADU",
  prefab: "Prefab / factory-built",
  two_story: "Two-story / above garage",
};
export const SERVICE_TYPE_LABELS = {
  design_build: "Design-build",
  general_contractor: "General contractor",
  prefab_manufacturer: "Prefab manufacturer",
  architect: "Architect / designer",
  permit_expediter: "Permit expediter",
};
export const APPROACH_LABELS = { custom: "Custom builds", prefab: "Prefab only", both: "Custom and prefab" };
export const BUILD_METHOD_LABELS = {
  site_built: "Site built",
  modular: "Modular",
  manufactured: "Manufactured or factory built",
  panelized: "Panelized",
  kit: "Kit",
};
export const PROFILE_STATUS_LABELS = {
  draft: "Draft",
  pending: "Pending review",
  approved: "Approved",
  inactive: "Inactive",
};
// The one sentence that explains the turnkey flag, shared by the admin form,
// the builder profile editor and the homeowner-facing pages so the meaning
// never drifts between surfaces.
export const TURNKEY_HELP = "Takes the project end to end, from selection and design through the build.";

// Raw event kinds in public.referral_events (0006). Stages are derived in
// reporting, never stored; "qualified lead" is deliberately not a concept here.
export const EVENT_KINDS = ["link_visited", "email_captured", "account_created", "package_purchased", "builder_profile_viewed", "builder_contacted", "project_signed"];
export const EVENT_KIND_LABELS = {
  link_visited: "Visits",
  email_captured: "Emails captured",
  account_created: "Sign ups",
  package_purchased: "Purchases",
  builder_profile_viewed: "Profile views",
  builder_contacted: "Introduction requests",
  project_signed: "Projects signed",
};

// A builder's share link. The code is generated by ADUAtlas on approval and
// never chosen or rotated by the builder.
export const REFERRAL_BASE_URL = "https://aduatlas.com/?ref=";
export const referralLink = (code) => (code ? `${REFERRAL_BASE_URL}${code}` : null);

export const publicUrl = (path) => {
  if (!supabaseEnabled || !path) return null;
  return supabase.storage.from(BUCKET).getPublicUrl(path).data.publicUrl;
};

const myAppUserId = async () => {
  if (!supabaseEnabled) return null;
  const { data: auth } = await supabase.auth.getUser();
  if (!auth?.user) return null;
  const { data } = await supabase.from("users").select("id").eq("auth_user_id", auth.user.id).maybeSingle();
  return data?.id || null;
};

// PostgREST reports a relation that is not in its schema cache as PGRST205;
// older versions surfaced Postgres's own 42P01. A missing RPC is PGRST202 or
// 42883. Both mean "migration 0006 is not applied yet", never a user error.
const isMissingRelation = (error) => Boolean(error) && (error.code === "42P01" || error.code === "PGRST205");
const isMissingFunction = (error) => Boolean(error) && (error.code === "42883" || error.code === "PGRST202");
const rpcError = (error) => (isMissingFunction(error) ? "not-available" : error.message);

// The directory columns exposed by builders_public (0006), verbatim. Nothing
// from the contact-name, account, referral, tracking, commercial or admin
// side of the record is in the view, so nothing here can ask for it.
export const PUBLIC_VIEW_COLUMNS = [
  "id", "slug", "name", "description", "logo_path", "website", "external_link",
  "contact_email", "contact_phone", "state", "city", "cities", "service_zips", "service_states",
  "specialties", "service_types", "build_approach", "build_methods", "turnkey", "licensed_states",
  "photos", "videos", "featured", "created_at",
].join(", ");

// Fallback for a database that has 0005 but not 0006: the column-level SELECT
// grant from 0005, verbatim. referral_code is deliberately absent, and
// Postgres rejects `select *` under column-level privileges, so the read must
// name its columns. Rows from this path have none of the 0006 fields; every
// consumer below treats them as empty.
export const HOMEOWNER_BUILDER_COLUMNS = [
  "id", "slug", "name", "description", "logo_path", "website", "external_link",
  "contact_email", "contact_phone", "state", "cities", "service_zips", "specialties",
  "service_types", "build_approach", "photos", "videos", "active", "featured",
  "created_at", "updated_at",
].join(", ");

// Directory. Filtering happens client-side on the (small) approved set so the
// search box feels instant.
export const fetchBuilders = async () => {
  if (!supabaseEnabled) return { ok: false, error: "supabase-disabled", items: [] };
  let { data, error } = await supabase.from(PUBLIC_VIEW).select(PUBLIC_VIEW_COLUMNS).order("featured", { ascending: false }).order("name");
  if (isMissingRelation(error)) {
    ({ data, error } = await supabase.from("builders").select(HOMEOWNER_BUILDER_COLUMNS).eq("active", true).order("featured", { ascending: false }).order("name"));
  }
  if (error) return { ok: false, error: error.message, items: [] };
  return { ok: true, items: data || [] };
};

export const fetchBuilder = async (slug) => {
  if (!supabaseEnabled) return { ok: false, error: "supabase-disabled" };
  let { data, error } = await supabase.from(PUBLIC_VIEW).select(PUBLIC_VIEW_COLUMNS).eq("slug", slug).maybeSingle();
  if (isMissingRelation(error)) {
    ({ data, error } = await supabase.from("builders").select(HOMEOWNER_BUILDER_COLUMNS).eq("slug", slug).maybeSingle());
  }
  if (error) return { ok: false, error: error.message };
  return { ok: true, builder: data || null };
};

export const fetchFeaturedBuilders = async () => {
  if (!supabaseEnabled) return [];
  const { data, error } = await supabase.rpc("get_featured_builders");
  return error ? [] : data || [];
};

export const fetchSaved = async () => {
  if (!supabaseEnabled) return new Set();
  const { data } = await supabase.from("saved_builders").select("builder_id");
  return new Set((data || []).map((r) => r.builder_id));
};

export const toggleSaved = async (builderId, saved) => {
  const userId = await myAppUserId();
  if (!userId) return { ok: false, error: "not-signed-in" };
  const q = saved
    ? supabase.from("saved_builders").delete().eq("user_id", userId).eq("builder_id", builderId)
    : supabase.from("saved_builders").insert({ user_id: userId, builder_id: builderId });
  const { error } = await q;
  return error ? { ok: false, error: error.message } : { ok: true, saved: !saved };
};

export const fetchMyIntros = async () => {
  if (!supabaseEnabled) return [];
  const { data } = await supabase.from("intro_requests").select("id, builder_id, status, created_at");
  return data || [];
};

// Records that the signed-in homeowner viewed or contacted a builder
// (log_builder_event, 0006). The server accepts only those two kinds, counts
// one a day per builder, and ignores builder accounts. Best effort: a failure
// (including "0006 not applied yet") is swallowed and never reaches the UI.
export const logBuilderEvent = async (builderId, kind) => {
  if (!supabaseEnabled || !builderId || !kind) return;
  try {
    await supabase.rpc("log_builder_event", { p_builder_id: builderId, p_kind: kind });
  } catch {
    // best effort only
  }
};

export const requestIntro = async (builderId, message) => {
  const userId = await myAppUserId();
  if (!userId) return { ok: false, error: "not-signed-in" };
  const { data, error } = await supabase
    .from("intro_requests")
    .insert({ user_id: userId, builder_id: builderId, message: (message || "").slice(0, 2000) || null })
    .select()
    .maybeSingle();
  if (error) return { ok: false, error: error.code === "23505" ? "already-requested" : error.message };
  await logBuilderEvent(builderId, "builder_contacted");
  return { ok: true, intro: data };
};

const wantsTurnkey = (v) => v === true || v === "yes" || v === "true";

// Directory filter. Order of the controls follows the call: State, then ADU
// type, then Turnkey, then the builder (search); Licensed state and Build
// method sit alongside. A state matches a builder's home state or any state
// in its service area; a licensed state matches licensed_states only.
export const filterBuilders = (items, { q = "", state = "", specialty = "", approach = "", turnkey, licensedState = "", buildMethod = "" } = {}) => {
  const needle = q.trim().toLowerCase();
  const st = (state || "").toUpperCase();
  const lic = (licensedState || "").toUpperCase();
  const turnkeyOnly = wantsTurnkey(turnkey);
  return items.filter((b) => {
    if (st && b.state !== st && !(b.service_states || []).includes(st)) return false;
    if (specialty && !(b.specialties || []).includes(specialty)) return false;
    if (turnkeyOnly && !b.turnkey) return false;
    if (lic && !(b.licensed_states || []).includes(lic)) return false;
    if (buildMethod && !(b.build_methods || []).includes(buildMethod)) return false;
    if (approach && b.build_approach !== "both" && b.build_approach !== approach) return false;
    if (!needle) return true;
    const hay = [b.name, b.state, b.city, ...(b.cities || []), ...(b.service_zips || [])].filter(Boolean).join(" ").toLowerCase();
    return hay.includes(needle);
  });
};

// Rank builders for a homeowner's property: same state or service state,
// then city or ZIP match, then the desired ADU type, then turnkey when the
// homeowner wants it and a license in the project's state. At most five.
//
// Only relevance signals decide whether a builder is suggested at all. A
// featured builder with nothing in common with the property is not a
// suggestion for it; featured only breaks ties among builders that already
// match, so a paid placement never shows up under "Suggested for <city>" on
// placement alone.
export const suggestForProperty = (items, { state, city, zip, aduType, turnkey } = {}) => {
  const type = (aduType || "").toLowerCase();
  const wanted = type.includes("garage") ? "garage_conversion" : type.includes("attach") ? "attached" : type.includes("prefab") || type.includes("modular") ? "prefab" : type.includes("jadu") || type.includes("interior") ? "jadu" : type.includes("detach") ? "detached" : null;
  const st = (state || "").toUpperCase();
  const turnkeyWanted = wantsTurnkey(turnkey);
  return items
    .map((b) => {
      let score = 0;
      if (st && (b.state === st || (b.service_states || []).includes(st))) score += 3;
      if (city && (b.cities || []).some((c) => c.toLowerCase() === city.toLowerCase())) score += 3;
      if (zip && (b.service_zips || []).some((z) => zip.startsWith(z))) score += 3;
      if (wanted && (b.specialties || []).includes(wanted)) score += 2;
      if (turnkeyWanted && b.turnkey) score += 2;
      if (st && (b.licensed_states || []).includes(st)) score += 2;
      return { b, score };
    })
    .filter((x) => x.score > 0)
    .sort((x, y) => y.score - x.score || Number(Boolean(y.b.featured)) - Number(Boolean(x.b.featured)) || (x.b.name || "").localeCompare(y.b.name || ""))
    .slice(0, MAX_SUGGESTIONS)
    .map((x) => x.b);
};

// "1247 Mulberry Ln, Pasadena, CA 91103" -> { city, state, zip }
export const parseAddress = (address = "") => {
  const m = address.match(/,\s*([^,]+?),\s*([A-Z]{2})\b\s*(\d{5})?/i);
  if (!m) return {};
  return { city: m[1].trim(), state: m[2].toUpperCase(), zip: m[3] || "" };
};

// ── Builder portal (role "pro") ─────────────────────────────────────────────
// Every call below resolves the caller's own builder row server-side. The
// row comes back without commercial_terms and admin_notes. `error` is
// "not-available" when 0006 is not applied yet, otherwise the server's plain
// English message (for example "company name is required").

// { ok, builder } where builder is null when the account has no profile yet.
export const fetchMyBuilder = async () => {
  if (!supabaseEnabled) return { ok: false, error: "supabase-disabled", builder: null };
  const { data, error } = await supabase.rpc("my_builder");
  if (error) return { ok: false, error: rpcError(error), builder: null };
  const row = Array.isArray(data) ? data[0] : data;
  return { ok: true, builder: row || null };
};

// Creates the profile as a draft on first save (name and state required) or
// updates it. Only these keys are read; anything else in the patch is ignored:
//   name, description, address_line, city, state, zip, contact_name,
//   contact_email, contact_phone, website, external_link, cities,
//   service_zips, service_states, specialties, service_types, build_approach,
//   build_methods, turnkey, licensed_states, videos
// Status, referral code, active, featured, photos, terms and audit fields are
// never writable from here.
export const saveMyBuilder = async (patch) => {
  if (!supabaseEnabled) return { ok: false, error: "supabase-disabled" };
  const { data, error } = await supabase.rpc("save_my_builder", { p: patch || {} });
  if (error) return { ok: false, error: rpcError(error) };
  return { ok: true, builder: data };
};

// draft -> pending. Approval is an admin action.
export const submitMyBuilder = async () => {
  if (!supabaseEnabled) return { ok: false, error: "supabase-disabled" };
  const { data, error } = await supabase.rpc("submit_my_builder");
  if (error) return { ok: false, error: rpcError(error) };
  return { ok: true, builder: data };
};

export const emptyReferralStats = () => ({
  counts: Object.fromEntries(EVENT_KINDS.map((k) => [k, 0])),
  referred_users_count: 0,
  purchased_amount_cents: 0,
});

// Aggregate counts for the caller's builder, zero-filled for every kind:
//   { counts: { link_visited, email_captured, account_created, package_purchased,
//               builder_profile_viewed, builder_contacted, project_signed },
//     referred_users_count, purchased_amount_cents }
// stats is null when the account has no profile yet. Nothing identifying.
export const fetchMyReferralStats = async () => {
  if (!supabaseEnabled) return { ok: false, error: "supabase-disabled", stats: null };
  const { data, error } = await supabase.rpc("my_referral_stats");
  if (error) return { ok: false, error: rpcError(error), stats: null };
  if (!data) return { ok: true, stats: null };
  const base = emptyReferralStats();
  const counts = { ...base.counts };
  for (const k of EVENT_KINDS) counts[k] = Number(data.counts?.[k]) || 0;
  return {
    ok: true,
    stats: {
      counts,
      referred_users_count: Number(data.referred_users_count) || 0,
      purchased_amount_cents: Number(data.purchased_amount_cents) || 0,
    },
  };
};
