-- =============================================================================
-- 0005 — Builder referral attribution (Phase 1 decisions 10 and 11, 2026-09-24)
--
-- Builder listings stay FREE in Phase 1: nothing here bills a builder and the
-- proposed listing fee is not implemented. What a participating builder gets
-- is attribution. Every profile carries a unique referral code that becomes a
-- share link (https://aduatlas.com/?ref=<code>). The code rides along the
-- homeowner journey (browser -> lead -> Stripe session metadata -> webhook)
-- and lands on users, so ADUAtlas can see which homeowners a builder referred
-- and which of them paid.
--
-- ATTRIBUTION ONLY. A commission of roughly 5% was discussed on the call and
-- is NOT finalized, so there is deliberately no payout, percentage, ledger or
-- balance anywhere in this schema. When the terms are agreed they belong in a
-- later migration, not here.
--
--   builders.referral_code          8 chars from A-HJ-NP-Z2-9 (no 0/O/1/I), unique
--   users.referred_by_builder_id    first-touch attribution, service role only
--   users.referral_code             the code as it arrived (audit trail)
--   users.referred_at               when the Stripe webhook stamped it
--   leads.referral_code             same pair on the pre-payment lead
--   leads.referred_by_builder_id
--   capture_lead(...)               now also takes p_referral_code
--   referral_stats()                per-builder lead and paid counts (service role)
--
-- Security model mirrors 0001: the attribution columns on users are written
-- only by the service role (api/stripe-webhook.js); a homeowner cannot assign
-- or clear their own referrer. builders.referral_code is hidden from
-- homeowners with a column-level select grant (see the note there).
-- =============================================================================

-- ── builders.referral_code ──────────────────────────────────────────────────
-- Generated by api/admin/_builders.js on create and never changed afterwards
-- (builders print the link). Existing profiles are backfilled below so every
-- builder has a link the moment this runs.
alter table public.builders
  add column referral_code text unique
    check (referral_code ~ '^[A-HJ-NP-Z2-9]{8}$');

do $$
declare
  r      record;
  v_code text;
begin
  for r in select id from public.builders where referral_code is null loop
    loop
      select string_agg(substr('ABCDEFGHJKLMNPQRSTUVWXYZ23456789', 1 + floor(random() * 32)::int, 1), '')
        into v_code
        from generate_series(1, 8);
      exit when not exists (select 1 from public.builders where referral_code = v_code);
    end loop;
    update public.builders set referral_code = v_code where id = r.id;
  end loop;
end
$$;

-- ── users: who referred this buyer ──────────────────────────────────────────
alter table public.users
  add column referred_by_builder_id uuid references public.builders (id) on delete set null,
  add column referral_code          text,
  add column referred_at            timestamptz;

create index users_referred_by_builder_id_idx on public.users (referred_by_builder_id);

-- 0001 grants UPDATE on users to authenticated per column (completed_chapters,
-- builder_packet, knowledge_result), so the new columns are already read-only
-- to the homeowner. The revoke below states that intent explicitly, the same
-- way the billing columns are service-role-only.
revoke update (referred_by_builder_id, referral_code, referred_at)
  on public.users from authenticated;

-- ── leads: attribution before payment ───────────────────────────────────────
alter table public.leads
  add column referral_code          text,
  add column referred_by_builder_id uuid references public.builders (id) on delete set null;

-- referral_stats() runs a correlated count on this column per builder, so it
-- gets the same index the users side has.
create index leads_referred_by_builder_id_idx on public.leads (referred_by_builder_id);

-- =============================================================================
-- capture_lead(): same RPC as 0001 plus an optional referral code. The old
-- signature is dropped first so PostgREST never has two candidates to pick
-- from. Callers that still pass three arguments keep working (default null).
-- =============================================================================
drop function if exists public.capture_lead(citext, text, jsonb);

create or replace function public.capture_lead(
  p_email         citext,
  p_source        text default 'unlock',
  p_quiz_answers  jsonb default null,
  p_referral_code text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id      uuid;
  v_code    text;
  v_builder uuid;
begin
  if p_email is null or position('@' in p_email) = 0 then
    raise exception 'invalid email';
  end if;

  -- Normalise and resolve the code (case-insensitive) to an ACTIVE builder. A
  -- malformed, unknown or inactive code is ignored, never an error: the lead
  -- still lands. The normalised code is kept even when it does not resolve so
  -- an admin can see what arrived.
  v_code := upper(nullif(trim(p_referral_code), ''));
  if v_code is not null and v_code ~ '^[A-HJ-NP-Z2-9]{8}$' then
    select b.id into v_builder
      from public.builders b
     where b.referral_code = v_code and b.active
     limit 1;
  else
    v_code := null;
  end if;

  insert into public.leads (email, source, quiz_answers, referral_code, referred_by_builder_id)
  values (lower(p_email), coalesce(p_source, 'unlock'), p_quiz_answers, v_code, v_builder)
  on conflict (email) do update
    set quiz_answers           = coalesce(excluded.quiz_answers, public.leads.quiz_answers),
        source                 = coalesce(excluded.source, public.leads.source),
        -- first touch wins: an existing attribution is never replaced
        referral_code          = coalesce(public.leads.referral_code, excluded.referral_code),
        referred_by_builder_id = coalesce(public.leads.referred_by_builder_id, excluded.referred_by_builder_id)
  returning id into v_id;

  return v_id;
end;
$$;

grant execute on function public.capture_lead(citext, text, jsonb, text)
  to anon, authenticated;

-- =============================================================================
-- Hide builders.referral_code from homeowners.
--
-- 0004 grants SELECT on the whole builders table to authenticated (the row
-- policy builders_select_paid limits WHICH rows). A code is not a secret in
-- the usual sense (builders hand it out in a link), but a paid homeowner
-- should not be able to harvest every builder's code and seed leads against
-- them. So the table-level grant becomes a column list that leaves
-- referral_code out. get_featured_builders() already names its columns and
-- does not include the code.
--
-- CLIENT NOTE: with column-level privileges Postgres rejects `select *`, so
-- the homeowner directory (src/lib/builders.js fetchBuilders / fetchBuilder)
-- must ask for these columns by name.
-- =============================================================================
revoke select on public.builders from authenticated;
grant select (
    id, slug, name, description, logo_path, website, external_link,
    contact_email, contact_phone, state, cities, service_zips, specialties,
    service_types, build_approach, photos, videos, active, featured,
    created_at, updated_at
  ) on public.builders to authenticated;

-- =============================================================================
-- referral_stats(): what the admin sees per builder. Counts only. No money.
-- Service role only: Supabase grants EXECUTE on new public functions to
-- anon/authenticated by default, so revoke that explicitly.
-- =============================================================================
create or replace function public.referral_stats()
returns table (
  builder_id    uuid,
  name          text,
  referral_code text,
  leads_count   integer,
  paid_count    integer,
  paid_by_tier  jsonb
)
language sql
security definer
set search_path = public
stable
as $$
  select
    b.id                                                         as builder_id,
    b.name,
    b.referral_code,
    (select count(*)::int
       from public.leads l
      where l.referred_by_builder_id = b.id)                     as leads_count,
    (select count(*)::int
       from public.users u
      where u.referred_by_builder_id = b.id
        and public.users_is_paid(u))                             as paid_count,
    coalesce((
      select jsonb_object_agg(t.paid_tier, t.n)
        from (
          select u.paid_tier, count(*)::int as n
            from public.users u
           where u.referred_by_builder_id = b.id
             and public.users_is_paid(u)
             and u.paid_tier is not null
           group by u.paid_tier
        ) t
    ), '{}'::jsonb)                                              as paid_by_tier
  from public.builders b
  order by b.name;
$$;

revoke execute on function public.referral_stats() from public, anon, authenticated;
grant  execute on function public.referral_stats() to service_role;

-- =============================================================================
-- Notes
--   • First touch wins everywhere: capture_lead keeps an existing lead
--     attribution, and the webhook only sets users.referred_by_builder_id
--     where it is still null, so Stripe retries and later upgrades never
--     re-attribute a buyer.
--   • A builder's code is never rotated by the app. If one ever has to be
--     retired, deactivate the builder (active = false): capture_lead and the
--     webhook both resolve codes against active builders only.
-- =============================================================================
